// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvWt_EHDsHoL9SHWvtsxWbUzwZD4SoUIM',
    appId: '1:728205489401:web:48c3191166e743f6869e28',
    messagingSenderId: '728205489401',
    projectId: 'mininggaurd',
    authDomain: 'mininggaurd.firebaseapp.com',
    storageBucket: 'mininggaurd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs3STKKIVdLIK6IZ8ajJFUCj6twkN5W3g',
    appId: '1:728205489401:android:7887ceaf6536e286869e28',
    messagingSenderId: '728205489401',
    projectId: 'mininggaurd',
    storageBucket: 'mininggaurd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvWt_EHDsHoL9SHWvtsxWbUzwZD4SoUIM',
    appId: '1:728205489401:web:fbad46feb71130d6869e28',
    messagingSenderId: '728205489401',
    projectId: 'mininggaurd',
    authDomain: 'mininggaurd.firebaseapp.com',
    storageBucket: 'mininggaurd.firebasestorage.app',
  );
}